#!/usr/bin/env node
// generate-data-js.js
// Deterministic generator: data/careers.json + data/taxonomy/*.json  ->  data/data.js
//
// data/data.js is the runtime mirror loaded by index.html from file:// (where fetch()
// of local JSON is blocked). It used to be hand-mirrored from the canonical JSON files
// (see the old note in data/data.js) — this script makes that mechanical and safe.
//
// Usage:  node scripts/generate-data-js.js
// Called automatically at the end of scripts/refresh-market-data.js.

'use strict';

const fs = require('fs');
const path = require('path');

const DATA_DIR = path.join(__dirname, '..', 'data');
const TAX_DIR = path.join(DATA_DIR, 'taxonomy');

function readJson(p) {
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}

function build() {
  const careers = readJson(path.join(DATA_DIR, 'careers.json'));
  const interests = readJson(path.join(TAX_DIR, 'interests.json'));
  const strengths = readJson(path.join(TAX_DIR, 'strengths.json'));
  const subjects = readJson(path.join(TAX_DIR, 'subjects.json'));
  const nirf = readJson(path.join(DATA_DIR, 'nirf-colleges.json'));

  // window.CAREER_DATA shape consumed by matcher.js / composer.js.
  // Keep keys identical to the original hand-written data.js (+ nirfColleges).
  const payload = {
    interestLabels: interests.labels,
    strengthLabels: strengths.labels,
    subjectLabels: subjects.labels,
    nirfColleges: nirf.categories,
    nirfYear: nirf._year,
    careers: careers.careers
  };

  const body = [
    '// AUTO-GENERATED by scripts/generate-data-js.js — DO NOT EDIT BY HAND.',
    '// Source of truth: data/careers.json + data/taxonomy/*.json',
    '// Regenerate with:  node scripts/generate-data-js.js',
    '// (Browsers block fetch() of local JSON from file:// — this mirror lets the app',
    '//  run from a plain file:// open and from Netlify identically.)',
    '',
    '(function () {',
    "  'use strict';",
    '',
    '  window.CAREER_DATA = {',
    '    interestLabels: ' + indent(JSON.stringify(payload.interestLabels, null, 2), 4) + ',',
    '    strengthLabels: ' + indent(JSON.stringify(payload.strengthLabels, null, 2), 4) + ',',
    '    subjectLabels: ' + indent(JSON.stringify(payload.subjectLabels, null, 2), 4) + ',',
    '    nirfColleges: ' + indent(JSON.stringify(payload.nirfColleges, null, 2), 4) + ',',
    '    nirfYear: ' + JSON.stringify(payload.nirfYear) + ',',
    '    careers: ' + indent(JSON.stringify(payload.careers, null, 2), 4),
    '  };',
    '',
    "  console.log('[CareerDisha] data.js loaded —', window.CAREER_DATA.careers.length, 'careers');",
    '})();',
    ''
  ].join('\n');

  return body;
}

// Re-indent a JSON.stringify block so nested lines line up under the assignment,
// without touching the first line.
function indent(jsonStr, spaces) {
  const pad = ' '.repeat(spaces);
  return jsonStr.split('\n').map((line, i) => (i === 0 ? line : pad + line)).join('\n');
}

function main() {
  const out = build();
  const dest = path.join(DATA_DIR, 'data.js');
  fs.writeFileSync(dest, out, 'utf8');
  const careerCount = readJson(path.join(DATA_DIR, 'careers.json')).careers.length;
  console.log('[generate-data-js] wrote ' + path.relative(process.cwd(), dest) + ' (' + careerCount + ' careers)');
}

if (require.main === module) main();

module.exports = { build };
